# Site settings
title: Endrons Blog
email: tk_rh@gmx.net
description: > # this means to ignore newlines until "baseurl:"
  Mein Blog in dem ich über Dinge rede, die ich interessant finde oder
  meine Beobachtunden die ich mit der Welt teilen möchte.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://endron.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
timezone: "Europe/Berlin"
markdown: kramdown
